---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/metallb
  - ./metallb/
# patches:
#   - path: __.yaml
#     target:
#       kind: HelmRelease
#       name: __
