apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.com/api
      identityURL: https://vault.bitwarden.com/identity
      auth:
        secretRef:
          credentials:
            name: bitwarden-access-token
            key: token
            namespace: external-secrets
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      organizationID: ef45391c-e654-4ac1-acab-b16e001e58b4
      projectID: d9ab22af-0c2a-4475-b1a5-b3e10112c001