---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
patches:
  - path: podinfo.yaml
    target:
      kind: HelmRelease
      name: podinfo
      namespace: default
