---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-baumannphoto-com-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: bane@sith.network
    privateKeySecretRef:
      name: letsencrypt-ct-teamworx-com-pk
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: CLOUDFLARE_API_KEY
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-baumannphoto-com
  namespace: cert-manager
spec:
  secretName: wildcard-baumannphoto-com
  issuerRef:
    name: letsencrypt-baumannphoto-com-issuer
    kind: ClusterIssuer
  commonName: "*.baumannphoto.com"
  dnsNames:
    - "*.baumannphoto.com"
    - "baumannphoto.com"