---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-sith-network-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: bane@sith.network
    privateKeySecretRef:
      name: letsencrypt-ct-teamworx-com-pk
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: CLOUDFLARE_API_KEY
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-sith-network
  namespace: cert-manager
spec:
  secretName: wildcard-sith-network
  issuerRef:
    name: letsencrypt-sith-network-issuer
    kind: ClusterIssuer
  commonName: "*.sith.network"
  dnsNames:
    - "*.sith.network"
    - "sith.network"