apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - es-cloudflare-api-token.yaml
  - issuer-sith-network.yaml
  - issuer-baumannphoto-com.yaml
  - issuer-brick-management.yaml